# Generated by Django 5.0.3 on 2024-03-24 22:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Weather', '0003_userpreference_user_alter_user_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('users', models.ManyToManyField(blank=True, related_name='cities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
