# Generated by Django 5.1.1 on 2024-09-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Weather', '0004_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='pressure',
        ),
        migrations.AddField(
            model_name='user',
            name='City',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='humidity',
            field=models.CharField(default='%', max_length=10),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='seaLevel',
            field=models.CharField(default='hPa', max_length=10),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='timezone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='city',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
