version: '3.8'

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A Weather_Backend worker --loglevel=info --pool=solo  # Pool solo avoids multi-threading issues in dev
    volumes:
      - .:/app  # Mount the local project to the /app folder
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - ENVIRONMENT=development
    depends_on:
      - redis
    user: myuser

  celery-beat:
    build: .
    command: celery -A Weather_Backend beat --loglevel=info
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - ENVIRONMENT=development
    depends_on:
      - redis
    user: myuser
